name: Create Image and Staging Tags

on:
  workflow_call:
    outputs:
      IMAGE_TAG:
        description: 'Immutable image tag'
        value: ${{ jobs.set_staging_tag.outputs.IMAGE_TAG }}
      STAGING_TAG:
        description: 'Staging namespace/tag'
        value: ${{ jobs.set_staging_tag.outputs.STAGING_TAG }}

jobs:
  set_staging_tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_image_tag.outputs.IMAGE_TAG }}
      STAGING_TAG: ${{ steps.set_staging_tag.outputs.STAGING_TAG }}
    steps:
      - name: Set IMAGE_TAG
        id: set_image_tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}-${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT

      - name: Set STAGING_TAG
        id: set_staging_tag
        run: echo "STAGING_TAG=staging-${GITHUB_SHA::7}-${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
